### PR TITLE
Merge transitive and direct reverse dependencies, close sbt/stb#5484

### PR DESCRIPTION
**Pull request by slandelle**
Motivation:

Direct reverse dependencies Map is added into the transitive reverse dependencies Map, so any dependency existing in both Maps loses transitive callers.

This behavior is not consistent with the ivy based lm and is not desirable: the goal is to have the complete callers tree.

Modification:

Merge the 2 maps instead of adding and lose values for conflicting keys.

Result:

Transitive callers are not lost when dependency is also pulled directly.

### CODE REVIEW

**Comment by slandelle** [comment]
CI failure is unrelated. It looks like master is broken.

**Comment by alexarchambault** [comment]
Also, once this is merged, and a release of sbt-coursier is cut with that, this will probably need an sbt release to be fixed out-of-the-box in sbt. If you're interested, you can benefit from it earlier, as soon as a release is cut for sbt-coursier, by using the [coursier-based sbt launcher](https://github.com/coursier/sbt-launcher/blob/master/README.md#how-to-use). Using it, add a `addSbtPlugin("io.get-coursier" % "sbt-lm-coursier" % "[replace with upcoming sbt-coursier release version]")` in `project/plugins.sbt`, and you'll be able to benefit from your changes.

**Comment by slandelle** [comment]
@alexarchambault Thanks, but how is one supposed to compile sbt-coursier?

```
sbt:sbt-coursier-root> compile
[error] stack trace is suppressed; run last lm-coursier / coursierResolutions for the full output
[error] stack trace is suppressed; run last sbt-coursier / coursierResolutions for the full output
[error] stack trace is suppressed; run last sbt-coursier-shared / coursierResolutions for the full output
[error] stack trace is suppressed; run last sbt-lm-coursier / coursierResolutions for the full output
[error] stack trace is suppressed; run last sbt-coursier-shared-shaded / coursierResolutions for the full output
[error] stack trace is suppressed; run last lm-coursier-shaded / coursierResolutions for the full output
[error] stack trace is suppressed; run last sbt-pgp-coursier / coursierResolutions for the full output
[error] stack trace is suppressed; run last sbt-shading / coursierResolutions for the full output
[error] stack trace is suppressed; run last coursierResolutions for the full output
[error] (lm-coursier / coursierResolutions) java.lang.NoSuchMethodError: lmcoursier.definitions.ToCoursier$.project(Llmcoursier/definitions/Project;)Lcoursier/core/Project;
[error] (sbt-coursier / coursierResolutions) java.lang.NoSuchMethodError: lmcoursier.definitions.ToCoursier$.project(Llmcoursier/definitions/Project;)Lcoursier/core/Project;
[error] (sbt-coursier-shared / coursierResolutions) java.lang.NoSuchMethodError: lmcoursier.definitions.ToCoursier$.project(Llmcoursier/definitions/Project;)Lcoursier/core/Project;
[error] (sbt-lm-coursier / coursierResolutions) java.lang.NoSuchMethodError: lmcoursier.definitions.ToCoursier$.project(Llmcoursier/definitions/Project;)Lcoursier/core/Project;
[error] (sbt-coursier-shared-shaded / coursierResolutions) java.lang.NoSuchMethodError: lmcoursier.definitions.ToCoursier$.project(Llmcoursier/definitions/Project;)Lcoursier/core/Project;
[error] (lm-coursier-shaded / coursierResolutions) java.lang.NoSuchMethodError: lmcoursier.definitions.ToCoursier$.project(Llmcoursier/definitions/Project;)Lcoursier/core/Project;
[error] (sbt-pgp-coursier / coursierResolutions) java.lang.NoSuchMethodError: lmcoursier.definitions.ToCoursier$.project(Llmcoursier/definitions/Project;)Lcoursier/core/Project;
[error] (sbt-shading / coursierResolutions) java.lang.NoSuchMethodError: lmcoursier.definitions.ToCoursier$.project(Llmcoursier/definitions/Project;)Lcoursier/core/Project;
[error] (coursierResolutions) java.lang.NoSuchMethodError: lmcoursier.definitions.ToCoursier$.project(Llmcoursier/definitions/Project;)Lcoursier/core/Project;
[error] Total time: 0 s, completed Mar 31, 2020 10:22:15 AM
sbt:sbt-coursier-root> last lm-coursier / coursierResolutions
[error] java.lang.NoSuchMethodError: lmcoursier.definitions.ToCoursier$.project(Llmcoursier/definitions/Project;)Lcoursier/core/Project;
[error] 	at coursier.sbtcoursier.ResolutionTasks$.$anonfun$resolutionsTask$3(ResolutionTasks.scala:43)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error] 	at sbt.Execute.work(Execute.scala:290)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (lm-coursier / coursierResolutions) java.lang.NoSuchMethodError: lmcoursier.definitions.ToCoursier$.project(Llmcoursier/definitions/Project;)Lcoursier/core/Project;
```

**Comment by slandelle** [comment]
@alexarchambault It looks like sbt-coursier can't be built with sbt 1.3 and one must use the sbt script at the project root. But because of this, I can't manage to import in latest IntelliJ (import crashes with the same failure as trying to compile with sbt 1.3 from the command line). Any tip?

**Comment by slandelle** [comment]
@alexarchambault Sorry, I'm really not familiar with scripted :(
I could validate that my PR fixes the issue on our side (thanks to [those instructions](https://get-coursier.io/docs/sbt-coursier.html#sbt-13x)).

**Comment by alexarchambault** [comment]
About the sbt launcher in IntelliJ, you cna generate a coursier-based sbt launcher *JAR* (not script, unlike the `sbt` file at the root of the repo here), with
```
$ cs bootstrap sbt-launcher -o sbt-launcher
```

You should then go in IntelliJ preferences, "Build, execution, deployment" > "Build tools" > "sbt", and there, in "Launcher (sbt-launch.jar)", check "Custom" and pass the `sbt-launcher` file generated above.

Sorry about that overall, I didn't realize the script that ships with sbt-coursier doesn't work from there.

**Comment by alexarchambault** [comment]
@slandelle I'll see if I can create a test case myself. Did you run into this issue with public repositories?

**Comment by alexarchambault** [comment]
Merging this right now, as this doesn't break any existing case anyway.

**Comment by alexarchambault** [comment]
I cut `2.0.0-RC6-3` with that. It's being built and released [on Travis CI](https://travis-ci.org/github/coursier/sbt-coursier/builds/669246303). As soon as this is released and sync-ed to Central, you should be able to use it via https://github.com/coursier/sbt-coursier/pull/209#issuecomment-606309286 or [the instructions](https://get-coursier.io/docs/sbt-coursier.html#sbt-13x) you refered to.

**Comment by slandelle** [comment]
> Did you run into this issue with public repositories?

A bit complicated :) https://github.com/gatling/sbt-frontline (commercial component, not documented). We scan dependencies tree to build a fatjar without all the dependencies that would be fetched transitively from Gatling modules. Without this fix, we for example see scala-library only pulled from root module while it's actually pulled transitively from Gatling and should be excluded.

> About the sbt launcher in IntelliJ, you cna generate a coursier-based sbt launcher JAR

Thanks for the tip :)

> I cut 2.0.0-RC6-3 with that.

Thanks a lot, it really help!
